#!/usr/bin/env python
"""Step 1 -- EAGLE-I outage data, the MCC denominator, and TIGER counties.

EAGLE-I 2014-2025 lives on figshare (doi 10.6084/m9.figshare.24237376) and is
fetchable over the API. The article was extended after the original Phase 1
run, so Phase 2 can fetch the frozen 2023 test year through the same endpoint.

Cannot slice server-side: the annual CSV is a single file. Download the year,
filter locally. Sub-GB, minutes.
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import pandas as pd
import requests

from src.common.config import PATHS, base_parser, config_from_args
from src.common.geo import fetch_counties
from src.common.io_outage import normalize_outage_frame
from src.common.logio import dir_size_mb, get_logger, record, timed

log = get_logger("01_fetch")
FIGSHARE_API = "https://api.figshare.com/v2/articles/{article}/files"


def figshare_files(article: int) -> dict[str, dict]:
    r = requests.get(FIGSHARE_API.format(article=article), timeout=60)
    r.raise_for_status()
    return {f["name"]: f for f in r.json()}


def download(url: str, dest: Path, expect_bytes: int | None = None) -> Path:
    if dest.exists() and (expect_bytes is None or dest.stat().st_size == expect_bytes):
        log.info("cached  %s (%.1f MB)", dest.name, dest.stat().st_size / 1e6)
        return dest
    log.info("GET %s", url)
    tmp = dest.with_suffix(dest.suffix + ".part")
    with requests.get(url, stream=True, timeout=1800) as r:
        r.raise_for_status()
        got = 0
        with open(tmp, "wb") as fh:
            for chunk in r.iter_content(chunk_size=1 << 20):
                fh.write(chunk)
                got += len(chunk)
                if got % (64 << 20) < (1 << 20):
                    log.info("  ... %.0f MB", got / 1e6)
    tmp.rename(dest)
    log.info("saved   %s (%.1f MB)", dest.name, dest.stat().st_size / 1e6)
    return dest


MANUAL = """
Could not reach figshare ({err}).

Download by hand and put the files in data/raw/ :
  EAGLE-I 2014-2025 : https://doi.org/10.6084/m9.figshare.24237376
      -> eaglei_outages_{year}.csv , MCC.csv , coverage_history.csv

Then re-run this step; it will find the cached files and skip the download.
"""


def fetch_eaglei(cfg, year: int) -> tuple[Path, Path]:
    outages = PATHS.raw / f"eaglei_outages_{year}.csv"
    mcc = PATHS.raw / "MCC.csv"
    if outages.exists() and mcc.exists():
        log.info("cached EAGLE-I %s and MCC.csv", year)
        return outages, mcc
    try:
        files = figshare_files(cfg["sources"]["eaglei_figshare_article"])
    except Exception as err:                                  # noqa: BLE001
        raise SystemExit(MANUAL.format(err=err, year=year)) from err

    for name, dest in ((f"eaglei_outages_{year}.csv", outages), ("MCC.csv", mcc)):
        if name not in files:
            raise SystemExit(
                f"{name} not in the figshare article. Available: "
                f"{sorted(files)}\n" + MANUAL.format(err="file missing", year=year))
        download(files[name]["download_url"], dest, files[name].get("size"))
    if "coverage_history.csv" in files:
        download(files["coverage_history.csv"]["download_url"],
                 PATHS.raw / "coverage_history.csv")
    return outages, mcc


def main() -> None:
    ap = base_parser(__doc__)
    ap.add_argument("--year", type=int, default=None,
                    help="EAGLE-I year to fetch (default: phase1 window_source_year)")
    args = ap.parse_args()
    cfg = config_from_args(args)
    year = args.year or int(cfg.get("window_source_year", 2019))

    if args.synthetic:
        log.warning("synthetic mode: outage CSV is generated by run_phase1, "
                    "not downloaded. Nothing to fetch.")
        return

    with timed("outage_download", log):
        outages, mcc = fetch_eaglei(cfg, year)
        counties = fetch_counties(cfg)
    record("outage_download", megabytes=dir_size_mb(outages) + dir_size_mb(mcc))

    df = normalize_outage_frame(pd.read_csv(outages, dtype={"fips_code": "string"}), cfg)
    log.info("%s: %s rows in state(s) %s, %d counties, %s -> %s",
             outages.name, f"{len(df):,}", cfg["state_fips"],
             df.fips_code.nunique(), df.run_start_time.min(), df.run_start_time.max())
    log.info("counties file: %s", Path(counties).name)
    log.info("MCC: %s", mcc.name)


if __name__ == "__main__":
    main()
