#!/usr/bin/env python
"""Gate criterion 10 -- one command, raw data to a decision number.

    make phase1              real data (needs ~/.cdsapirc and the EAGLE-I CSV)
    make phase1-synthetic    generated stand-in data, no credentials, ~30 s

Writes docs/phase1_report.md: the section 7 go/no-go table and the section 8
measurements table, both filled in from this run. That report is the handoff
artifact -- Phase 2 starts only when every criterion in it says PASS.
"""
from __future__ import annotations

import argparse
import os
import runpy
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import pandas as pd
import yaml

from src.common.config import PATHS, ROOT, load_config
from src.common.gates import GateBook, GateFailure, book, criteria_report
from src.common.logio import get_logger, measurements_markdown, record

log = get_logger("run_phase1")
SRC = ROOT / "src"
def report_path() -> Path:
    ns = os.environ.get("STORM_DATA_NS", "").strip()
    return ROOT / "docs" / (f"phase1_report{ns}.md" if ns else "phase1_report.md")

STEPS = [
    ("03_build_events.py", "outage event table"),
    ("04_build_features.py", "weather features + the correlation that proves the premise"),
    ("05_fit_models.py", "three model stages in degenerate mode"),
    ("06_compose_mc.py", "Monte Carlo composition"),
    ("07_forecast_cases.py", "GEFS forecast, one lead time"),
    ("08_decision_value.py", "cost-loss and break-even"),
]
SYNTH_START = "2019-07-19"          # inside the configured training window


def run_step(script: str, cfg_path: str, phase1_path: str) -> None:
    log.info("=" * 70)
    log.info("STEP %s", script)
    argv = sys.argv
    sys.argv = [str(SRC / script), "--config", cfg_path, "--phase1", phase1_path]
    try:
        runpy.run_path(str(SRC / script), run_name="__main__")
    finally:
        sys.argv = argv


def write_synthetic_config(phase1_path: Path, start: str, days: int) -> Path:
    raw = yaml.safe_load(phase1_path.read_text())
    raw["window_start"] = start
    raw["window_end"] = str((pd.Timestamp(start) + pd.Timedelta(days=days)).date())
    raw["_synthetic"] = True
    out = ROOT / "config" / "_phase1_synthetic.yaml"
    out.write_text("# GENERATED by run_phase1.py --synthetic. Do not edit; not committed.\n"
                   + yaml.safe_dump(raw, sort_keys=False))
    return out


def make_report(cfg, ok: bool, elapsed: float) -> Path:
    table, _ = criteria_report()
    overrides = sorted(yaml.safe_load(Path(cfg["_phase1_file"]).read_text()))
    report = report_path()
    report.parent.mkdir(exist_ok=True)
    report.write_text(f"""# Phase 1 report -- {cfg['region_name']}

Generated {pd.Timestamp.utcnow():%Y-%m-%d %H:%M UTC} in {elapsed / 60:.1f} min.
Window `{cfg.get('window_start')}` .. `{cfg.get('window_end')}` ({cfg['window_days']} days).

**Nothing in this report is a result.** Five days gives too few independent
storm observations for validation, regardless of the exact event count. No
coefficient, AUC, CRPS or dollar figure below means anything. The only question
this report answers is whether the code executes and the outputs have valid
structure.

## Section 7 -- go / no-go

{table}

**Overall: {'GO -- Phase 2 may start' if ok else 'NO-GO -- do not start Phase 2'}**

Criterion 6 is the real gate. Criteria 1-5 and 7-10 test whether the code runs;
6 tests whether the premise holds in this data -- that public county-level
outage records carry a recoverable weather signal.

## Section 8 -- measurements

{measurements_markdown()}

If the projected ERA5 aggregation exceeds a few hours, precompute the
cell-to-county weight matrix once as a sparse array and apply it as a single
matrix multiply per timestep (already done in `src/common/geo.py`). If projected
memory exceeds available RAM, switch to Dask with time chunking now, while the
pipeline is small.

## Section 9 -- handoff checklist

- [ ] Revert every `config/phase1.yaml` override: `make phase1-diff` lists them
      ({len(overrides)} keys).
- [ ] Restore the 30-day rolling baseline (`baseline_method: rolling`).
- [ ] `make clean-phase1` -- delete every fitted model and figure. They are
      contaminated by a relaxed threshold and a one-day validation split.
- [ ] Keep: download code, join logic, weight matrix, assertion suite, this table.
- [ ] `make test` -- the assertions are now a test module that runs on every
      Phase 2 execution.
- [ ] Confirm `region.yaml` splits match the current frozen Phase 2 design and
      that nothing in Phase 1 touched 2023.
""")
    return report


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--config", default=str(ROOT / "config" / "region.yaml"))
    ap.add_argument("--phase1", default=str(ROOT / "config" / "phase1.yaml"))
    ap.add_argument("--synthetic", action="store_true")
    ap.add_argument("--report-only", action="store_true")
    args = ap.parse_args()

    if args.synthetic:
        # every synthetic artifact lives under a "_synthetic" namespace so it can
        # never be mistaken for a cached real download
        os.environ["STORM_DATA_NS"] = "_synthetic"

    if args.report_only:
        table, ok = criteria_report()
        print(table)
        print("\n" + measurements_markdown())
        sys.exit(0 if ok else 1)

    PATHS.ensure()
    GateBook.reset()
    phase1_path = Path(args.phase1)
    t0 = time.perf_counter()

    if args.synthetic:
        cfg0 = load_config(args.config, phase1_path)
        phase1_path = write_synthetic_config(
            phase1_path, SYNTH_START, int(cfg0["window_days"]))
        from src.common.synthetic import generate_all
        cfg = load_config(args.config, phase1_path)
        log.warning("SYNTHETIC MODE -- generated data. Proves plumbing only; "
                    "no number produced here refers to anything real.")
        generate_all(cfg, pd.Timestamp(SYNTH_START), int(cfg["window_days"]),
                     int(cfg["n_gefs_members"]), cfg.get("gefs_lead_hours", [0, 24, 48]))
    else:
        cfg = load_config(args.config, phase1_path)
        if str(cfg.get("window_start", "AUTO")) == "AUTO":
            log.info("window_start is AUTO -- running window selection first")
            run_step("select_window.py", args.config, str(phase1_path))
            raise SystemExit(
                "Window selected. Re-run `make window` with --write (or `python "
                "src/select_window.py --write`), then `make fetch`, `make weather`, "
                "then `make phase1`.")
        run_step("01_fetch_outage.py", args.config, str(phase1_path))
        run_step("02_fetch_weather.py", args.config, str(phase1_path))

    gb = book("run_phase1")
    failed = None
    try:
        for script, what in STEPS:
            log.info(">>> %s", what)
            run_step(script, args.config, str(phase1_path))
    except GateFailure as err:
        failed = err
        log.error("GATE FAILURE: %s", err)
        log.error("The spec says stop here. Do not proceed on a soft failure "
                  "hoping the next step fixes it.")
    except SystemExit as err:
        if err.code not in (0, None):
            failed = err
            log.error("step exited: %s", err)

    elapsed = time.perf_counter() - t0
    gb.check("end_to_end_single_command", failed is None,
             f"`make phase1{'-synthetic' if args.synthetic else ''}` "
             f"{'completed' if failed is None else 'stopped: ' + str(failed)[:120]} "
             f"in {elapsed / 60:.1f} min", criterion=10)
    meas = measurements_markdown()
    gb.check("measurements_recorded", "_not measured_" not in meas,
             "section 8 table filled in from this run", criterion=11)
    gb.flush()
    record("run_phase1", elapsed_min=round(elapsed / 60, 2), synthetic=args.synthetic)

    table, ok = criteria_report()
    path = make_report(cfg, ok, elapsed)
    print("\n" + table + "\n")
    print(f"report -> {path}")
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
